### ISSUE TITLE
[BUG] Can't install rl4co in CPython3.11

### ISSUE THREAD

**Issue by hyeok9855** [kaist-silab/rl4co#90]
## Describe the bug

Can't install rl4co with `pip install rl4co` or `pip install -e .` in CPython3.11.

This is because torchrl is not supported in CPython3.11 (see this [torchrl issue](https://github.com/pytorch/rl/issues/1423)).

## To Reproduce

Please refer to the [torchrl issue](https://github.com/pytorch/rl/issues/1423).

## Screenshots

![image](https://github.com/kaist-silab/rl4co/assets/40595684/927df128-8db9-4f21-b1f9-ea49d6fb3fa9)

## Reason and Possible fixes

Maybe specify the right python version that works (e.g. 3.10)?

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by fedebotu** [comment]
Hi @hyeok9855 ! Thanks for dropping by. We are aware of the issue and indeed for the time being we are also [not testing on the latest Python version](https://github.com/kaist-silab/rl4co/actions) because of this problem. 
Python 3.11 was recently introduced [here](https://github.com/pytorch/rl/issues/1469) in the TorchRL nightlies, so we plan to wait for the latest stable version of TorchRL! 
Let's specify the Python version in `pyproject.toml` for now :)
